baseURL = "http://plutokaito.github.io"
languageCode = "en"
DefaultContentLanguage = "cn"
title = "KaitoShy's 万事屋"
theme ="anatole"
enableEmoji = true
enableRobotsTXT = true
summarylength = 1
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title="I'm KaitoShy"
author="KaitoShy"
description = "Java And PHP Developer"
keywords="java php"
fullPostContent = false
mainSections = ["post"]
profilePicture = "images/avatar.png"
doNotLoadAnimations = false
readMore = true
displayMode = "dark"
copyright = "KaitoShy 2021 - {{ YEAR }}"


[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/plutokaito"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:kaito78@163.com"

[params.simpleAnalytics]
enable = true

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[menu]
  [[menu.main]]
  name = "主页(Home)"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "博客(Blog)"
  weight = 200
  identifier = "post"
  url = "/post/"

  [[menu.main]]
  name = "关于(About)"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "联系(Contact)"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
  name="标签(tags)"
  weight=400
  identifier="tags"
  url="/tags/"
