baseURL = "http://plutokaito.github.io"
languageCode = "ZH-CN"
title = "KaitoShy's 万事屋"
theme ="anatole"
enableEmoji = true
enableRobotsTXT = true

[params]
title="I'm KaitoShy"
author="KaitoShy"
description = "Java And PHP Developer"
keywords="java php go"
fullPostContent = false
mainSections = ["post"]
profilePicture = "images/avatar.png"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/plutokaito"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:kaito78@163.com"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
  name="tags"
  weight=400
  identifier="tags"
  url="/tags/"
